name: Build
permissions:
  contents: write
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Update checksum
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile checksum
        run: |
          make --no-print-directory compile
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'gpt'
          default_author: github_actions
          message: 'ci: automatic code generation'
